# Generated by Django 5.0.4 on 2024-05-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
